#! /bin/sh

########## BSPWM ###########
bspc monitor -d 1 2 3 4

bspc config normal_border_color 	"#272727"
bspc config active_border_color 	"#272727"
bspc config focused_border_color 	"#ffffff"
bspc config presel_feedback_color "#596d6e"

bspc config border_width         	1
bspc config window_gap          	8
bspc config top_padding         	34
bspc config left_padding         	6
bspc config right_padding        	6
bspc config bottom_padding       	6

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a Zathura state=tiled

########## STARTUP ###########
sxhkd -c ~/.config/sxhkd/haruhi &
picom --config ~/.config/picom/mi &
feh --bg-fill ~/Pictures/Wallpaper/mi.png &
xsetroot -cursor_name left_ptr &
polybar -c ~/.config/polybar/mi mi &
setxkbmap -option caps:swapescape  &
dunst -config ~/.config/dunst/dunstrc-haruhi &
xrdb ~/.config/Xresources/mi &
redshift -x -PO 5600 &
#theme-zathura-sh haruhi &
sleep 2
#~/.scripts/tewi-fortune.sh &
pulseaudio -D &
