#! /bin/sh

########## BSPWM ###########
bspc monitor -d 1 2 3 4

bspc config normal_border_color 	"#050505"
bspc config active_border_color 	"#050505"
bspc config focused_border_color 	"#e4d7bd"
bspc config presel_feedback_color "#e4d7bd"

bspc config border_width         	2
bspc config window_gap          	12
bspc config top_padding         	50
bspc config left_padding         	20
bspc config right_padding        	20
bspc config bottom_padding       	20

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a Zathura state=tiled

########## STARTUP ###########
sxhkd -c ~/.config/sxhkd/soren &
picom --config ~/.config/picom/soren &
feh --bg-fill ~/Pictures/Wallpaper/goya_witches_sabbath.png &
xsetroot -cursor_name left_ptr &
polybar -c ~/.config/polybar/soren soren &
setxkbmap -option caps:swapescape  &
dunst -config ~/.config/dunst/dunstrc-soren &
xrdb ~/.config/Xresources/soren &
redshift -x -PO 5600 &
theme-zathura-sh soren-light &
sleep 2
pulseaudio -D &
