#! /bin/sh

# Startup
~/.scripts/extend &
sxhkd &
pkill pulseaudio &
compton --config ~/.config/compton/config --respect-prop-shadow --shadow-exclude-reg=1920x19+0+0 &
feh --bg-fill /tmp/out.png &
xsetroot -cursor_name left_ptr &
~/.scripts/reverse_trackpoint.sh &
pasystray &
nm-applet &
xfce4-power-manager &
#cbatticon &
redshift -PO 5700 &
xbacklight -set 63 &
pactl set-sink-volume 1 40 &
#pactl set-sink-mute 0 1 &
setxkbmap -option caps:swapescape &
polybar dark &
xrdb .Xresources.zenburn &
#unclutter --timeout 4 &
mpv /usr/share/sounds/elementary/stereo/dialog-information.wav &
xinput --set-prop 10 'libinput Accel Profile Enabled' 0, 1 &
xinput --set-prop 12 'libinput Accel Profile Enabled' 0, 1 &
nitrogen --restore &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap         	 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a libreoffice* state=tiled
bspc rule -a Wine* state=floating
bspc rule -a Steam* state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
