#! /bin/sh

########## BSPWM ###########
bspc monitor -d 1 2 3 4

bspc config normal_border_color 	"#1c913b"
bspc config active_border_color 	"#1c913b"
bspc config focused_border_color 	"#00ff60"

bspc config border_width         	2
bspc config window_gap          	24

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

#bspc rule -a .* state=tiled follow=off

########## STARTUP ###########
sxhkd -c ~/.config/sxhkd/sxhkdrc-neon &
picom --config ~/.config/compton.conf.neon &
feh --bg-fill ~/Pictures/Wallpaper/reisen-udongein-inaba.png &
xsetroot -cursor_name left_ptr &
polybar -c ~/.config/polybar/config-neon neon &
setxkbmap -option caps:swapescape  &
dunst -config ~/.config/dunst/dunstrc-purp &
xrdb ~/.Xresources_isotope &
redshift -x -PO 5600 &
sleep 2
~/.scripts/tewi-fortune.sh &
pulseaudio -D &
